name: CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lancer les tests
        run: pytest -q
      - name: Notification Discord (succès)
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
            -d "{\"content\":\"✅ CI réussie sur la branche ${{ github.ref_name }} par ${{ github.actor }}\"}" \
            ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Notification Discord (échec)
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
            -d "{\"content\":\"❌ CI échouée sur la branche ${{ github.ref_name }} par ${{ github.actor }}\"}" \
            ${{ secrets.DISCORD_WEBHOOK_URL }}
